// vue-remote/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: vue-remote</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
    <Counter/>
  </div>
</template>

<script>
import Counter from "./Counter.vue"

export default {
  components: {
    Counter
  }
}
</script>

// host/src/App.jsx
import React, {useRef, useEffect} from "react";
import ReactDOM from "react-dom";

import "./index.scss";

import Counter from "remote/Counter";
import counterMounter from "vue_remote/counterMounter";

const App = () => {
	const ref = useRef(null);

	useEffect(() => {
		counterMounter(ref.current);
	}, []);

	return (
		<div className="mt-10 text-3xl mx-auto max-w-6xl">
			<div className="">Name: host</div>
			<div>Framework: react</div>
			<div>Language: JavaScript</div>
			<div>CSS: Tailwind</div>
			<Counter />
			<div ref={ref}></div>
		</div>
	);
};
ReactDOM.render(<App />, document.getElementById("app"));
