// vue-remote/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: vue-remote</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
    <Counter/>
  </div>
</template>

<script>
import Counter from "./Counter.vue"

export default {
  components: {
    Counter
  }
}
</script>

// remote/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";

import "./index.scss";
import Counter from "./Counter";

const App = () => (
	<div className="mt-10 text-3xl mx-auto max-w-6xl">
		<div>Name: remote</div>
		<div>Framework: react</div>
		<div>Language: JavaScript</div>
		<div>CSS: Tailwind</div>
		<Counter />
	</div>
);
ReactDOM.render(<App />, document.getElementById("app"));
